import json

missing_translations = {
  "project.step_reading_script": "Reading your script...",
  "project.step_identify_chars": "Identifying characters & context...",
  "project.step_building_scenes": "Building scenes...",
  "project.step_optimizing": "Optimizing prompts for Veo...",
  "project.step_starting_render": "Initializing & starting render...",
  "project.audio": "Audio",
  "project.audio_voiceover": "Voiceover (AI voice)",
  "project.audio_voiceover_desc": "Voice overlays video — clear audio, no lip-sync",
  "project.audio_character_speak": "Character speaking",
  "project.audio_character_speak_desc": "Veo lip-syncs character to voice (voice quality may vary)",
  "project.audio_off": "No audio",
  "project.audio_off_desc": "Video only",
  "project.generating_portraits": "Generating character model sheet...",
  "project.enter_idea_first": "Enter your idea first",
  "project.confirm_create": "Create {{n}} scenes — costs approx {{cost}} 💎. Continue?",
  "project.error_create_prompt": "Error creating prompts",
  "project.paste_script_first": "Paste your script first",
  "project.error_parse_script": "Error parsing script",
  "project.paste_prompts_first": "Paste your prompts first",
  "project.no_valid_prompt": "No valid prompt found",
  "project.select_storyboard_first": "Select a storyboard image or PDF first",
  "project.storyboard_no_frames": "Could not extract any frames from storyboard — try a clearer image.",
  "project.error_read_storyboard": "Error reading storyboard",
  "project.need_name_and_photo": "Character name and photo required",
  "project.add_char_failed": "Failed to add character",
  "project.write_script_first": "Write script first",
  "project.default_name": "Project",
  "project.create_project_failed": "Failed to create project",
  "project.need_at_least_one_scene": "Enter at least 1 scene with a prompt",
  "project.create_video_failed": "Failed to create video",
  "project.enter_url": "Enter URL",
  "project.analysis_failed": "Analysis failed",
  "project.confirm_delete": "Delete this project?",
  "project.overlay_building": "Building movie from your script — just a few seconds ☕",
  "project.create_video": "Create video",
  "project.tab_new": "From idea",
  "project.tab_batch": "From scene descriptions",
  "project.tab_copy": "Copy Idea",
  "project.tab_sell": "Sales Video",
  "project.new_header": "From idea — AI writes script & renders automatically",
  "project.project_name": "Project name",
  "project.project_name_placeholder": "Name of your movie...",
  "project.mode_ai": "AI writes",
  "project.mode_manual": "Manual script",
  "project.mode_prompts": "Paste Prompts",
  "project.mode_storyboard": "Read storyboard",
  "project.storyboard_select": "Select storyboard image or PDF",
  "project.storyboard_desc": "Grid image, multiple images, or PDF. AI reads each frame → writes prompt + dialogue. Scenes = frames. Max 10 files, ~18MB.",
  "project.placeholder_manual": "Paste your script (with dialogue + character names)...\nEx:\nScene 1: Mom sitting at the spa counter, looking tired.\nDialogue (Mom): \"No customers all day...\"\nScene 2: Son walks in...",
  "project.placeholder_prompts": "Paste your prompt list (1 line = 1 prompt = 1 scene)...\nEx:\nA cinematic shot of a mountain at sunset\nA person walking in the snow\n...",
  "project.placeholder_ai": "Describe your idea — the more detailed, the better the AI will write...",
  "project.scene_count": "Scenes",
  "project.fast_create": "fast",
  "project.duration_per_scene": "Duration / scene",
  "project.video_quality": "Video quality",
  "project.aspect_ratio": "Aspect ratio",
  "project.language": "Language",
  "project.face_lock": "Face lock",
  "project.face_lock_hint": "Add a photo to keep the character's face consistent across scenes.",
  "project.face_lock_tooltip": "Upload a photo for the AI to maintain the character's face",
  "project.face_lock_clone_hint": "Add a character photo to keep the EXACT face across all clone scenes.",
  "project.close": "close",
  "project.add_character": "add character",
  "project.char_name_placeholder": "Name (e.g., hero)",
  "project.select_photo": "📁 Select photo",
  "project.save": "Save",
  "project.assign_voice": "Assign voice to selected characters",
  "project.review_script": "Review detailed script",
  "project.reading_storyboard": "Reading storyboard...",
  "project.analyzing_creating": "Analyzing & creating...",
  "project.creating": "Creating...",
  "project.cta_storyboard": "Read storyboard & create movie →",
  "project.cta_manual": "Analyze & create movie →",
  "project.cta_prompts": "Create movie from Prompts →",
  "project.cta_ai": "AI writes & creates movie →",
  "project.video_length": "Video length",
  "project.cost": "Cost",
  "project.locked_faces": "🔒 locked {{count}} faces",
  "project.char_list_title": "Character List (Face & Voice)",
  "project.auto_drawing": "Auto drawing...",
  "project.ai_auto_portrait": "-- AI auto portrait --",
  "project.upload_new_photo": "+ Upload new photo...",
  "project.drawing": "Drawing...",
  "project.error_create_photo": "Error creating photo",
  "project.redraw_ai": "Redraw AI photo",
  "project.upload_error": "Upload error!",
  "project.ai_writing_script": "🪄 AI is writing a {{count}}-scene script — just a few seconds...",
  "project.detailed_script": "📝 Detailed script · {{count}} scenes — edit before creating:",
  "project.edit_back": "Edit again",
  "project.save_draft": "Save draft",
  "project.confirm_create_free": "Create a {{n}}-scene video using the Free model — NO credits required (0 💎). Continue?",
  "project.confirm_create_paid": "Create a {{n}}-scene video — costs approx {{cost}} 💎. Continue?",
  "project.initializing": "Initializing...",
  "project.create_and_merge": "🚀 Create & Merge video",
  "project.video_name_placeholder": "Your video name...",
  "project.batch_desc": "🎬 Each block = 1 SCENE — they will be merged into 1 movie automatically. Use @Name to lock character faces.",
  "project.batch_scene_placeholder": "Describe this scene (image + action)...",
  "project.narrator": "Narrator",
  "project.batch_narration_placeholder": "🔊 Dialogue (optional — for voiceover)",
  "project.options": "Options",
  "project.chain_mode": "Chain to previous scene (next scene starts from the last frame of the previous one)",
  "project.voice_read": "Voiceover",
  "project.char_voice_assign": "Character Voice Assignment",
  "project.copy_header": "Copy Idea — clone source video → new script, direct render",
  "project.video_link": "Video link",
  "project.frame": "Frame",
  "project.frame_vertical": "9:16 — Vertical (TikTok / Reels)",
  "project.frame_horizontal": "16:9 — Horizontal (YouTube)",
  "project.frame_square": "1:1 — Square",
  "project.visual_style": "Visual style",
  "project.keep_original_style": "Keep original style",
  "project.copy_est": "{{count}} scenes · {{aspect}}",
  "project.analyzing_creating_film": "Analyzing & creating movie...",
  "project.create_film_now": "🚀 Create movie now →",
  "scene.label": "Scene {{index}}",
  "scene.image_desc": "Image description",
  "scene.action": "Action",
  "scene.dialogue": "Dialogue",
  "scene.speaker": "Speaker",
  "scene.dialogue_placeholder": "Dialogue...",
  "scene.edit_prompt": "Scene description — edit if needed",
  "scene.describe": "Describe scene",
  "scene.narration_placeholder": "🔊 Dialogue / narration",
  "scene.add": "Add scene"
}

with open('frontend/src/locales/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

en.update(missing_translations)

with open('frontend/src/locales/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, indent=2, ensure_ascii=False)

print("Done injecting missing translations!")
